[2023-05-07T14:08:42.541-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2023-05-07T16:00:00+00:00 [queued]>
[2023-05-07T14:08:42.553-0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2023-05-07T16:00:00+00:00 [queued]>
[2023-05-07T14:08:42.553-0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T14:08:42.553-0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-07T14:08:42.554-0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T14:08:42.571-0300] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): inaccurate> on 2023-05-07 16:00:00+00:00
[2023-05-07T14:08:42.590-0300] {standard_task_runner.py:55} INFO - Started process 472 to run task
[2023-05-07T14:08:42.601-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world_dag', 'inaccurate', 'scheduled__2023-05-07T16:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_falopa.py', '--cfg-path', '/tmp/tmpg9dwngke']
[2023-05-07T14:08:42.606-0300] {standard_task_runner.py:83} INFO - Job 46: Subtask inaccurate
[2023-05-07T14:08:42.697-0300] {task_command.py:389} INFO - Running <TaskInstance: hello_world_dag.inaccurate scheduled__2023-05-07T16:00:00+00:00 [running]> on host DESKTOP-02TA80M.localdomain
[2023-05-07T14:08:42.770-0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=hello_world_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T16:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-07T16:00:00+00:00
[2023-05-07T14:08:42.774-0300] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-07T14:08:42.775-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2023-05-07T14:08:42.802-0300] {subprocess.py:86} INFO - Output:
[2023-05-07T14:08:42.819-0300] {subprocess.py:93} INFO - inaccurate
[2023-05-07T14:08:42.819-0300] {subprocess.py:97} INFO - Command exited with return code 0
[2023-05-07T14:08:42.853-0300] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=hello_world_dag, task_id=inaccurate, execution_date=20230507T160000, start_date=20230507T170842, end_date=20230507T170842
[2023-05-07T14:08:42.892-0300] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-05-07T14:08:42.914-0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
